apiVersion: v1
kind: Service
metadata:
  name: {{ template "airflow.fullname" . }}-airflow-web
  labels:
    app: {{ template "airflow.name" . }}-airflow-web
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.airflow.service.type }}
  selector:
    app: {{ template "airflow.name" . }}-airflow-web
    release: {{ .Release.Name }}
  ports:
    - name: web
      protocol: TCP
      port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "airflow.fullname" . }}-airflow-flower
  labels:
    app: {{ template "airflow.name" . }}-airflow-flower
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.airflow.service.type }}
  selector:
    app: {{ template "airflow.name" . }}-airflow-flower
    release: {{ .Release.Name }}
  ports:
    - name: flower
      protocol: TCP
      port: 5555
---
# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: {{ template "airflow.fullname" . }}-airflow-worker
  labels:
    app: {{ template "airflow.name" . }}-airflow-worker
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: worker
      protocol: TCP
      port: 8793
  clusterIP: None
  selector:
    app: {{ template "airflow.name" . }}-airflow-worker
